// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChSyYjox31qbqhtYDVb5W7eDsQQAFNrok',
    appId: '1:479996813513:web:1eede32eead6180953ed18',
    messagingSenderId: '479996813513',
    projectId: 'sahayog-aaf08',
    authDomain: 'sahayog-aaf08.firebaseapp.com',
    storageBucket: 'sahayog-aaf08.firebasestorage.app',
    measurementId: 'G-8G2H4PX5J3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqNwMzO4cYZIhh9axtlww5-VzgvKPNAuc',
    appId: '1:479996813513:android:eb165b34cef849b453ed18',
    messagingSenderId: '479996813513',
    projectId: 'sahayog-aaf08',
    storageBucket: 'sahayog-aaf08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBajxqx1wAWZqBHWm3nmZAX_vmUYMK2kYM',
    appId: '1:479996813513:ios:bf351cf425861e8e53ed18',
    messagingSenderId: '479996813513',
    projectId: 'sahayog-aaf08',
    storageBucket: 'sahayog-aaf08.firebasestorage.app',
    iosBundleId: 'com.example.sahayog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBajxqx1wAWZqBHWm3nmZAX_vmUYMK2kYM',
    appId: '1:479996813513:ios:bf351cf425861e8e53ed18',
    messagingSenderId: '479996813513',
    projectId: 'sahayog-aaf08',
    storageBucket: 'sahayog-aaf08.firebasestorage.app',
    iosBundleId: 'com.example.sahayog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChSyYjox31qbqhtYDVb5W7eDsQQAFNrok',
    appId: '1:479996813513:web:3793a19d76129bfa53ed18',
    messagingSenderId: '479996813513',
    projectId: 'sahayog-aaf08',
    authDomain: 'sahayog-aaf08.firebaseapp.com',
    storageBucket: 'sahayog-aaf08.firebasestorage.app',
    measurementId: 'G-N8NHH76ZRV',
  );
}
