// filepath: c:\Users\susma\Documents\sahayog\lib\firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
///